#%RAML 0.8
title: eternity API
version: 1.0
baseUri: http://api.eternity.com/

schemas:
   - image: !include schemas/common/image-schema.json
   - address: !include schemas/common/address-schema.json
   - frameworkAgreement: !include schemas/frameworkAgreement-schema.json
   - agreement: !include schemas/agreement-schema.json
   - contactor: !include schemas/contactor-schema.json
   - salesStaff: !include schemas/salesStaff-schema.json
   - employee: !include schemas/employee-schema.json
   - update: !include schemas/update-schema.json

   - subject: !include schemas/subject-schema.json
   - subjectUpdate: !include schemas/subjectUpdate-schema.json
   - subjects: !include schemas/subjects-schema.json
   - topic: !include schemas/topic-schema.json
   - topicSection: !include schemas/topicSection-schema.json
   - topicUpdate: !include schemas/topicUpdate-schema.json
   - topics: !include schemas/topics-schema.json
   - section: !include schemas/section-schema.json
   - sections: !include schemas/sections-schema.json
   - card: !include schemas/card-schema.json
   - cards: !include schemas/cards-schema.json
   - cardStyle: !include schemas/cardStyle-schema.json
   - cardStyles: !include schemas/cardStyles-schema.json
   - cardMaterial: !include schemas/cardMaterial-schema.json
   - cardCapability: !include schemas/cardCapability-schema.json
   - cardTemplate: !include schemas/cardTemplate-schema.json
   - cardTemplates: !include schemas/cardTemplates-schema.json
   - prop: !include schemas/prop-schema.json
   - props: !include schemas/props-schema.json
   - propStyle: !include schemas/propStyle-schema.json
   - propMaterial: !include schemas/propMaterial-schema.json
   - propCapability: !include schemas/propCapability-schema.json
   - propTemplate: !include schemas/propTemplate-schema.json
   - propTemplates: !include schemas/propTemplates-schema.json
   - product: !include schemas/product-schema.json
   - products: !include schemas/products-schema.json
   - productPrice: !include schemas/productPrice-schema.json
   - productLeaveTime: !include schemas/productLeaveTime-schema.json
   - medal: !include schemas/medal-schema.json
   - medals: !include schemas/medals-schema.json
   - medalStyle: !include schemas/medalStyle-schema.json
   - medalMaterial: !include schemas/medalMaterial-schema.json
   - medalCapability: !include schemas/medalCapability-schema.json
   - medalTemplate: !include schemas/medalTemplate-schema.json
   - medalTemplates: !include schemas/medalTemplates-schema.json
   - task: !include schemas/task-schema.json
   - tasks: !include schemas/tasks-schema.json
   - taskTemplate: !include schemas/taskTemplate-schema.json
   - lineSupplier: !include schemas/lineSupplier-schema.json
   - lineSuppliers: !include schemas/lineSuppliers-schema.json
   - contentSupplier: !include schemas/contentSupplier-schema.json
   - contentSuppliers: !include schemas/contentSuppliers-schema.json


resourceTypes:
  - base: !include resourceTypes/base.raml
  - collection: !include resourceTypes/collections.raml
  - typedCollection: !include resourceTypes/typeCollection.raml
  - member: !include resourceTypes/member.raml
  - typedMember: !include resourceTypes/typedMember.raml

traits:
  - paged : !include traits/page.raml
  - field: !include traits/fieldSelector.raml
  - keywords: !include traits/keywords.raml


/subjects:
  type : collection
  get:
    queryParameters:
      name:
        type: string
    responses:
      200:
        body:
          application/json:
            schema: subjects
  post:
    body:
      application/x-www-form-urlencoded:
        schema: !include schemas/common/address-schema.json
    responses:
      200:
        body:
          application/json:
            schema: subject
  /{subjectId}:
    type: member
    get:
      is: [field]
      responses:
        200:
          body:
            application/json:
              schema: subject
    /updateName:
      type: member
      put:
        description: update subject name
        body:
          application/json:
            schema: subjectUpdate
        responses:
          200:
            body:
              application/json:
                schema: update
/topics:
  type: collection
  get:
    queryParameters:
      name:
        type: string
    responses:
      200:
        body:
          application/json:
            schema: topics
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          name:
            type: string
            required: true
          maxQuantity:
            type: number
            required: true
          minQuantity:
            type: number
            required: true
          maxAge:
            type: number
            required: true
    responses:
      200:
        body:
          application/json:
            schema: topic
  /{topicId}:
    type: member
    get:
      is: [field]
      responses:
        200:
          body:
            application/json:
              schema: topic
    put:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            name:
              type: string
              required: true
            maxQuantity:
              type: integer
              required: true
            minQuantity:
              type: integer
              required: true
            maxAge:
              type: integer
              required: true
      responses:
        200:
          body:
            application/json:
              schema: update
    /settings:
      /setupSubject:
        type: member
        put:
          body:
            application/x-www-form-urlencoded:
              formParameters:
                subjectId:
                  type: string
                  required: true
          responses:
            200:
              body:
                application/json:
                  schema: update
      /setupSection:
        type: member
        put:
          body:
            application/json:
              schema: topicSection
          responses:
            200:
              body:
                application/json:
                  schema: update
