get?:
   responses: &standardResponses
     200:
      description: OK
     401:
      description: error
     500:
      description: bibi
put?:
   responses: *standardResponses
patch?:
   responses: *standardResponses
post?:
   responses:
     201:
   description: Created
delete?:
   responses: *standardResponses
