get?:
  responses: &standardResponses
    200:
  description: OK
put?:
   responses: *standardResponses
patch?:
   responses: *standardResponses
post?:
   responses:
     201:
   description: Created
delete?:
   responses: *standardResponses
