type: member
get:
  responses:
    200:
      body:
        application/json:
          schema: <<schema>>
put?:
  body:
    application/json:
      schema: <<schema>>
  responses:
    200:
      body:
        application/json:
          schema: <<schema>>
patch?:
  body:
    application/json:
      schema: <<schema>>
  responses:
    200:
      body:
        application/json:
          schema: <<schema>>
delete?:
