description: |
  LinkedIn supports OAuth 2.0 for authenticating all API requests.
type: OAuth 2.0
describedBy: 
   headers:
       Authorization:
           description: |
              Used to send a valid OAuth 2 access token. Do not use
              with the "access_token" query string parameter.
           type: string
settings: 
  authorizationUri: https://www.linkedin.com/uas/oauth2/authorization
  accessTokenUri: https://www.linkedin.com/uas/oauth2/accessToken
  authorizationGrants: [ code ]
