/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class personal_JNI_HelloWorld */

#ifndef _Included_personal_JNI_HelloWorld
#define _Included_personal_JNI_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     personal_JNI_HelloWorld
 * Method:    displayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_personal_JNI_HelloWorld_displayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
