displayName: paged
queryParameters:
  start:
    displayName: start
    description: The first page to return
    type: integer
  pages:
    displayName: pages
    description: The number of pages to return
    type: integer
